Added sqlite3
hydrastro/sadbot pull request #1
Opened 2021-04-26 21:07 UTC by meguminloli

Create the database using the createdatabase.sh . On Windows, just copy the command. It will generate a file called `message.db`, the sqlite3 database.

2021-04-26 23:23 UTC, hydrastro commented on bot.py
> +token = "1794848670:AAEzdrn_7BzpbWEPBX8rcCHvPvuH8q44Yfw"
This token should be replaced with a placeholder: token = "placeholder"

2021-04-26 23:24 UTC, hydrastro commented on bot.py
>  buffer_size = 1000
with sqlite support, this variable is useless, and should be removed

2021-04-26 23:26 UTC, hydrastro commented on bot.py
> +            elif message.endswith("g"):
this statement needs to be removed (is it a debugging leftover?)

2021-04-26 23:26 UTC, hydrastro commented on test.sql
> +SELECT * FROM messages;
this file can be removed

2021-04-26 23:31 UTC, hydrastro requested changes
Good work!
We're close to merging,
Just tell me if I should merge this now and change these things later or if you want to do it instead (it would be neater)

2021-04-26 23:31 UTC, hydrastro commented on createdatabase.sh
> +cat createdb.sql | sqlite3 messages.db
We could put this in `README.md`, what do you think?
Also I think we should remove `messages.db`

2021-04-27 09:36 UTC, meguminloli commented on bot.py
> +            elif message.endswith("g"):
no, it's the global selector in sed, maybe someone is a tryhard

2021-04-27 09:36 UTC, meguminloli commented on createdatabase.sh
> +cat createdb.sql | sqlite3 messages.db
ok

2021-04-27 09:49 UTC, meguminloli commented
Now, it should be done.

2021-04-27 09:53 UTC, hydrastro commented on bot.py
> +            elif message.endswith("g"):
oh, got it. Nice!

2021-04-27 09:54 UTC, hydrastro approved these changes

2021-04-27 09:54 UTC, merged